---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- name: Define apache_daemon.
  set_fact:
    apache_daemon: "{{ __apache_daemon }}"
  when: apache_daemon is not defined

# Setup/install tasks.
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
