---
- name: Ensure Apache is installed on Debian.
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apache_packages }}"

- name: Config
  copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
    owner: www-data
    group: www-data

- name: Copy htaccess file
  copy:
    src: htaccess
    dest: /var/www/html/.htaccess
    owner: www-data
    group: www-data

- name: Enable mode_rewrite
  shell: a2enmod rewrite
  notify: restart apache
